import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next"; // Import the getServerSession function, which will fetch the user's session
import { authOptions } from "@/pages/api/auth/[...nextauth]"; // Import the authOptions object, which contains the NextAuth.js configuration
import Hydrate from "./components/Hydrate"; // Import the Hydrate component to prevent React hydration errors
import { Roboto } from "next/font/google";

// Define main font
const roboto = Roboto({weight: ['400', '500', '700'], subsets: ['latin']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Fetch the user
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`mx-4 lg:mx-48 ${roboto.className}`}>
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string} />
        {children}
        </Hydrate>
      </body>
    </html>
  );
}
